#!/bin/bash

scp setup-disk root@dcatest03.fnal.gov:/diska/pool1/setup  
scp setup-disk root@dcatest03.fnal.gov:/diskb/pool2/setup
scp setup-disk root@dcatest03.fnal.gov:/diskc/pool3/setup
scp setup-disk root@dcatest03.fnal.gov:/diskd/pool4/setup
scp setup-disk root@dcatest03.fnal.gov:/diske/pool5/setup
scp setup-disk root@dcatest03.fnal.gov:/diskf/pool6/setup
scp setup-tape root@dcatest03.fnal.gov:/diskg/pool7/setup
scp setup-tape root@dcatest03.fnal.gov:/diskh/pool8/setup
scp setup-disk root@dcatest04.fnal.gov:/diska/pool1/setup
scp setup-disk root@dcatest04.fnal.gov:/diskb/pool2/setup
scp setup-disk root@dcatest04.fnal.gov:/diskc/pool3/setup
scp setup-disk root@dcatest04.fnal.gov:/diskd/pool4/setup
scp setup-disk root@dcatest04.fnal.gov:/diske/pool5/setup
scp setup-disk root@dcatest04.fnal.gov:/diskf/pool6/setup
scp setup-tape root@dcatest04.fnal.gov:/diskg/pool7/setup
scp setup-tape root@dcatest04.fnal.gov:/diskh/pool8/setup
scp setup-disk root@dcatest05.fnal.gov:/diska/pool1/setup
scp setup-disk root@dcatest05.fnal.gov:/diskb/pool2/setup
scp setup-disk root@dcatest06.fnal.gov:/diska/pool1/setup
scp setup-disk root@dcatest06.fnal.gov:/diskb/pool2/setup
scp setup-disk root@dcatest07.fnal.gov:/diska/pool1/setup
scp setup-disk root@dcatest07.fnal.gov:/diskb/pool2/setup
scp setup-disk root@dcatest07.fnal.gov:/diskc/pool3/setup
scp setup-disk root@dcatest07.fnal.gov:/diskd/pool4/setup
scp setup-disk root@dcatest08.fnal.gov:/diska/pool1/setup
scp setup-disk root@dcatest08.fnal.gov:/diskb/pool2/setup
scp setup-disk root@dcatest08.fnal.gov:/diskc/pool3/setup
scp setup-disk root@dcatest08.fnal.gov:/diskd/pool4/setup
scp setup-disk root@dcatest08.fnal.gov:/diske/pool5/setup
scp setup-disk root@dcatest08.fnal.gov:/diskf/pool6/setup
scp setup-tape root@dcatest08.fnal.gov:/diskg/pool7/setup
scp setup-tape root@dcatest08.fnal.gov:/diskh/pool8/setup
scp setup-disk root@dcatest09.fnal.gov:/diska/pool1/setup   
scp setup-disk root@dcatest09.fnal.gov:/diskb/pool2/setup 
scp setup-disk root@dcatest09.fnal.gov:/diskc/pool3/setup
scp setup-disk root@dcatest09.fnal.gov:/diskd/pool4/setup
scp setup-disk root@dcatest09.fnal.gov:/diske/pool5/setup
scp setup-disk root@dcatest09.fnal.gov:/diskf/pool6/setup
scp setup-tape root@dcatest09.fnal.gov:/diskg/pool7/setup
scp setup-tape root@dcatest09.fnal.gov:/diskh/pool8/setup